[package]
name = "ctb2"
version = "0.1.0"
authors = ["neilljohnston30@gmail.com <neilljohnston30@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tetris = { path = "tetris" }
rand = "0.7.3"